### ISSUE TITLE
前辈您好

### ISSUE THREAD

**Issue by shanhexing6** [ly2013203742/WBDS#1]
前辈您好，我是一名地信专业的大二学生。日前我在esri竞赛官网上看到您当年的竞赛项目获得2016届的最佳技能奖，并且对您的项目非常感兴趣，作为一个GIS初学者，想尝试学习一下您的项目。第一步便是获取微博签到数据，在研究如何获取的过程中在网上正好搜索到了您github关于微博数据分析的项目，看到介绍和esri官网上的一样，想必您便是当年聊城大学获奖的前辈。但是由于我根基尚浅，基本看不懂您的项目，项目介绍也是马马虎虎一知半解，所以如果方便的话，想请您留一下您的联系方式，向您请教，倘若您不方便在github上交流的话，（jiecong_xing@163.com）这是我的邮箱，您可以通过邮件告知您的联系方式，还望前辈不吝赐教。_

**Comment by swaggyPYang** [comment]
微博签到数据已经没法去获取了，另外我这个项目可能也不太适合入门看，因为代码会比较粗糙。您如果是webgis开发的话，您直接看arcgis js api 的官网比较好https://developers.arcgis.com/javascript/，另外有什么问题你可以加我q1547094768
